import { Toaster } from "@/components/ui/sonner";
import { cn } from "@/functions/cn";
import ThemeProvider from "@/providers/theme-provider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import type { ReactNode } from "react";
import "./globals.css";

const inter = Inter({
	variable: "--font-inter",
	subsets: ["latin"],
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

interface IRootLayout {
	children: ReactNode;
}

export default function RootLayout({ children }: Readonly<IRootLayout>) {
	return (
		<html
			lang="pt-BR"
			className={cn("antialiased scroll-smooth", inter.className)}
		>
			<body>
				<ThemeProvider>
					{children}
					<Toaster visibleToasts={9} richColors />
				</ThemeProvider>
			</body>
		</html>
	);
}
